server:
  port: 8084

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: agencia
  resource: user-management-service
  public-client: true
  bearer-only: true

custom:
  keycloak:
    rest:
      client:
        server-url: "http://localhost:8080/auth/"
        realm: "agencia"
        clientId: "agencia"
        clientSecret: ENC(ipX7VKf4SSffzKLnpUS2E1PBABr0Wz1S2k110Pjweqb+09rq3BBKwmOceFaxKeu6)


