server:
  port: 8084

keycloak:
  auth-server-url: "http://localhost:8080/auth"
  realm: agencia
  resource: user-management-service
  public-client: false
  use-resource-role-mappings: true
  enabled: true
  credentials:
    secret: ENC(fvHsTFCqrBi/TtzTi+mwfQNoagMm1YZDNR/TflDZD2bac0+P6IXjY/TQyDGK67GEG0Uixh0Qm34Pye3TF2ebyT+rjRbvlv3VLQCVPHjC7TY=)
  bearer-only: true

custom:
  keycloak:
    rest:
      client:
        server-url: "http://localhost:8080/auth/"
        realm: "agencia"
        clientId: "agencia"
        clientSecret: ENC(ipX7VKf4SSffzKLnpUS2E1PBABr0Wz1S2k110Pjweqb+09rq3BBKwmOceFaxKeu6)


