server:
  port: 8084

spring:
  application:
    name: user-management-service
  profiles:
    active: dev
  cloud:
    config:
      enabled: true
  config:
    import: optional:configserver:https://agencia-config-server.herokuapp.com



